In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import Thermobar as pt
import sympy as sym
pd.options.display.max_columns = None

In [2]:
LiqT=pd.DataFrame(data={"SiO2_Liq": 51,
                            "TiO2_Liq": 0.48,
                            "Al2O3_Liq": 19,
                            "FeOt_Liq": 5.3,
                            "MnO_Liq": 0.1,
                            "MgO_Liq": 4.5,
                            "CaO_Liq": 9,
                            "Na2O_Liq": 4.2,
                            "K2O_Liq": 0.1,
                            "Cr2O3_Liq": 0.11,
                            "P2O5_Liq": 0.11,
                            "H2O_Liq": 5,
                            "Fe3Fet_Liq":0.1,
}, index=[0])

LiqT_Err=pd.DataFrame(data={"SiO2_Liq_Err": 51,
                            "TiO2_Liq_Err": 0.48,
                            "Al2O3_Liq_Err": 19,
                            "FeOt_Liq_Err": 5.3,
                            "MnO_Liq_Err": 0.1,
                            "MgO_Liq_Err": 4.5,
                            "CaO_Liq_Err": 9,
                            "Na2O_Liq_Err": 4.2,
                            "K2O_Liq_Err": 0.1,
                            "Cr2O3_Liq_Err": 0.11,
                            "P2O5_Liq_Err": 0.11,
                            "H2O_Liq_Err": 5,
                            "Fe3Fet_Liq_Err":0.1,
}, index=[0])


OlT=pd.DataFrame(data={"SiO2_Ol": 40.5,
                            "TiO2_Ol": 0.02,
                            "Al2O3_Ol": 0.08,
                            "FeOt_Ol": 12.40,
                            "MnO_Ol": 0.17,
                            "MgO_Ol": 47.4,
                            "CaO_Ol": 0.30,
                            "Na2O_Ol": 0,
                            "K2O_Ol": 0,
                            "Cr2O3_Ol": 0.03},  index=[0])


SpT=pd.DataFrame(data={"SiO2_Sp": 0,
                            "TiO2_Sp": 0.248333,
                            "Al2O3_Sp":40.09866,
                            "FeOt_Sp": 11.805333,
                            "MnO_Sp": 0.16866,
                            "MgO_Sp": 19.131667,
                            "CaO_Sp": 0.006667,
                            "Na2O_Sp": 0.000667,
                            "K2O_Sp": 0,
                            "Cr2O3_Sp": 27.107333,
                            "NiO_Sp": 0.239000}, index=[0])

In [4]:
Liquids_only_abs_noise=pt.add_noise_sample_1phase(phase_comp=LiqT, phase_err=LiqT_Err, 
                                             phase_err_type="Abs", duplicates=1000, err_dist="uniform")
Liquids_only_abs_noise

All negative numbers replaced with zeros. If you wish to keep these, set positive=False

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,Cr2O3_Liq,P2O5_Liq,H2O_Liq,Fe3Fet_Liq,Sample_ID_Liq_Num
0,82.885507,0.959987,21.589966,2.728364,0.147761,7.698629,12.164677,5.882563,0.076190,0.040559,0.102448,6.385875,0.064274,0.0
1,92.558149,0.241604,5.004776,3.285757,0.106366,3.281177,2.866054,6.191886,0.174965,0.092337,0.137921,2.259200,0.126173,0.0
2,91.550990,0.479698,28.057439,0.028125,0.056822,4.980084,4.410210,7.234752,0.162179,0.201032,0.206201,8.916351,0.147611,0.0
3,60.729051,0.399386,10.496785,2.915732,0.033371,2.199406,7.115332,1.295676,0.093398,0.182044,0.149007,6.652647,0.071313,0.0
4,50.238008,0.275822,15.686452,10.273985,0.046486,0.432243,0.005666,6.139819,0.021447,0.219491,0.196224,4.309749,0.062862,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,92.853874,0.392010,26.653972,0.727351,0.002840,6.666815,5.683854,0.103270,0.059920,0.154834,0.000009,7.287738,0.051001,0.0
996,31.576821,0.303231,36.323961,9.344868,0.137445,8.327454,14.497581,0.534858,0.073733,0.030019,0.016848,4.286427,0.102065,0.0
997,62.645151,0.067396,22.006432,3.535886,0.043114,2.217137,14.301840,1.702445,0.059103,0.168557,0.154911,7.602670,0.020731,0.0
998,73.691991,0.774332,35.485087,2.484169,0.104918,3.672448,4.527820,6.584822,0.024050,0.188820,0.064152,5.860922,0.164550,0.0
999,15.576319,0.130985,33.252968,2.871387,0.145184,0.009172,4.920883,6.874743,0.018998,0.168064,0.008609,4.581175,0.103815,0.0

In [5]:
## CAnt think of a way to unit test this - as dont have random seed?