# Olivine-Liquid Hygrometry

- You need to install Thermobar once on your machine, if you haven't done this yet, uncomment the line below (remove the #)

In [2]:
#!pip install Thermobar

In [3]:
# Loading various python things
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import Thermobar as pt

In [4]:
# Setting plotting parameters
# This sets some plotting things
plt.rcParams["font.family"] = 'arial'
plt.rcParams["font.size"] =12
plt.rcParams["mathtext.default"] = "regular"
plt.rcParams["mathtext.fontset"] = "dejavusans"
plt.rcParams['patch.linewidth'] = 1
plt.rcParams['axes.linewidth'] = 1 
plt.rcParams["xtick.direction"] = "in"
plt.rcParams["ytick.direction"] = "in"
plt.rcParams["ytick.direction"] = "in"
plt.rcParams["xtick.major.size"] = 6 # Sets length of ticks
plt.rcParams["ytick.major.size"] = 4 # Sets length of ticks
plt.rcParams["ytick.labelsize"] = 12 # Sets size of numbers on tick marks
plt.rcParams["xtick.labelsize"] = 12 # Sets size of numbers on tick marks
plt.rcParams["axes.titlesize"] = 14 # Overall title
plt.rcParams["axes.labelsize"] = 14 # Axes labels

## Step 1 - load data

In [5]:
out=pt.import_excel('Liquid_only_Thermometry.xlsx', sheet_name="Ol-Liq")
my_input=out['my_input']
myLiquids1=out['Liqs']
myOls1=out['Ols']
display(myOls1.head())
display(myLiquids1.head())

,SiO2_Ol,TiO2_Ol,Al2O3_Ol,FeOt_Ol,MnO_Ol,MgO_Ol,CaO_Ol,Na2O_Ol,K2O_Ol,Cr2O3_Ol,NiO_Ol
0,40.5,0.02,0.08,12.40,0.17,47.4,0.30,0.0,0,0.03,0.0
1,41.3,0.03,0.11,9.59,0.14,50.2,0.31,0.0,0,0.00,0.0
2,39.7,0.05,0.11,15.60,0.18,44.5,0.31,0.0,0,0.03,0.0
3,40.5,0.05,0.10,13.20,0.18,46.8,0.29,0.0,0,0.02,0.0
4,40.5,0.00,0.10,9.41,0.10,49.3,0.31,0.0,0,0.00,0.0

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,Cr2O3_Liq,P2O5_Liq,H2O_Liq,Fe3Fet_Liq,NiO_Liq,CoO_Liq,CO2_Liq,Sample_ID_Liq
0,57.023602,0.623106,16.332899,4.36174,0.103851,4.19180,6.94858,3.59702,0.896895,0.000000,0.226584,5.59,0.2,0.0,0.0,0.0,0
1,57.658600,0.654150,17.194799,3.90621,0.084105,2.86892,5.91538,3.85948,1.018600,0.000000,0.214935,6.55,0.2,0.0,0.0,0.0,1
2,60.731201,0.862054,17.144199,4.07781,0.077488,2.50867,5.22075,4.45556,1.414160,0.000000,0.319638,3.14,0.2,0.0,0.0,0.0,2
3,61.532799,0.440860,16.508801,3.32990,0.037520,1.64150,4.34294,4.40860,1.407000,0.000000,0.215740,6.20,0.2,0.0,0.0,0.0,3
4,52.969101,0.803412,17.563000,5.93217,0.149472,3.78351,7.65110,3.80219,0.551178,0.037368,0.196182,6.58,0.2,0.0,0.0,0.0,4

## Example 1 - Simple calculation for just the H2O content of the liquid
- outputs just the wt% H2O in the liquid, using the hygrometer of Gavrilenko et al. (2016)

In [6]:
H2O_Calc_Thermobar=pt.calculate_ol_liq_hygr(liq_comps=myLiquids1, ol_comps=myOls1, 
                                               equationH="H_Gavr2016")
H2O_Calc_Thermobar

0    2.030582
1    1.364482
2    0.344844
3   -0.344697
4    2.860205
5    1.508569
6   -1.769123
7    1.909273
8    0.834843
9    2.860872
dtype: float64

## Example 2 - Calculating equilibrium tests
- In this example, we calculate equilibrium tests, as water contents calculated from non-equilibrium pairs are likely to be nonsense.
- P and T needed for Toplis Kd parameterization, here we enter fixed values

In [7]:
H2O_Calc_Thermobar_eqTest1=pt.calculate_ol_liq_hygr(liq_comps=myLiquids1, ol_comps=myOls1, 
                                               equationH="H_Gavr2016", eq_tests=True, P=1, T=1300)
H2O_Calc_Thermobar_eqTest1

,H2O_calc,Temp used for calcs,P used for calcs,Kd Meas,Kd calc (Toplis),"ΔKd, Toplis","ΔKd, Roeder","ΔKd, Matzen",SiO2_Ol,TiO2_Ol,...,Mg_Number_Liq_Fe3,Si_Ol_cat_frac,Mg_Ol_cat_frac,Fet_Ol_cat_frac,Ca_Ol_cat_frac,Al_Ol_cat_frac,Na_Ol_cat_frac,K_Ol_cat_frac,Mn_Ol_cat_frac,Ti_Ol_cat_frac
0,2.030582,1300,1,0.314264,0.326180,0.011916,0.014264,0.025736,40.5,0.02,...,0.681666,0.331677,0.578691,0.084925,0.002632,0.000772,0.0,0.0,0.001179,0.000123
1,1.364482,1300,1,0.175383,0.321910,0.146527,0.124617,0.164617,41.3,0.03,...,0.620707,0.331038,0.599846,0.064284,0.002662,0.001039,0.0,0.0,0.000950,0.000181
2,0.344844,1300,1,0.269582,0.314838,0.045256,0.030418,0.070418,39.7,0.05,...,0.578196,0.331560,0.554039,0.108956,0.002774,0.001083,0.0,0.0,0.001273,0.000314
3,-0.344697,1300,1,0.173799,0.314138,0.140339,0.126201,0.166201,40.5,0.05,...,0.523445,0.332170,0.572216,0.090539,0.002548,0.000967,0.0,0.0,0.001250,0.000309
4,2.860205,1300,1,0.152172,0.328355,0.176184,0.147828,0.187828,40.5,0.00,...,0.586967,0.330886,0.600452,0.064294,0.002714,0.000963,0.0,0.0,0.000692,0.000000
5,1.508569,1300,1,0.159554,0.332767,0.173213,0.140446,0.180446,40.5,0.02,...,0.565465,0.331178,0.591229,0.072488,0.002979,0.000964,0.0,0.0,0.001039,0.000123
6,-1.769123,1300,1,0.215915,0.342292,0.126376,0.084085,0.124085,40.2,0.04,...,0.528731,0.334056,0.552506,0.106326,0.003650,0.002155,0.0,0.0,0.001056,0.000250
7,1.909273,1300,1,0.404699,0.412296,0.007597,0.104699,0.064699,39.6,0.04,...,0.620033,0.333016,0.530297,0.131513,0.002973,0.000595,0.0,0.0,0.001353,0.000253
8,0.834843,1300,1,0.314115,0.391918,0.077802,0.014115,0.025885,39.8,0.05,...,0.583864,0.334067,0.539307,0.120735,0.003417,0.000594,0.0,0.0,0.001564,0.000316
9,2.860872,1300,1,0.429135,0.289064,0.140072,0.129135,0.089135,39.7,0.03,...,0.665729,0.330714,0.546417,0.117735,0.002945,0.000589,0.0,0.0,0.001411,0.000188

### Can filter outputs, so only get calculated H2O contents for those with delta Kd Roeder <0.1

In [8]:
InEq=H2O_Calc_Thermobar_eqTest1.loc[H2O_Calc_Thermobar_eqTest1['ΔKd, Roeder']<0.1]
InEq

,H2O_calc,Temp used for calcs,P used for calcs,Kd Meas,Kd calc (Toplis),"ΔKd, Toplis","ΔKd, Roeder","ΔKd, Matzen",SiO2_Ol,TiO2_Ol,...,Mg_Number_Liq_Fe3,Si_Ol_cat_frac,Mg_Ol_cat_frac,Fet_Ol_cat_frac,Ca_Ol_cat_frac,Al_Ol_cat_frac,Na_Ol_cat_frac,K_Ol_cat_frac,Mn_Ol_cat_frac,Ti_Ol_cat_frac
0,2.030582,1300,1,0.314264,0.326180,0.011916,0.014264,0.025736,40.5,0.02,...,0.681666,0.331677,0.578691,0.084925,0.002632,0.000772,0.0,0.0,0.001179,0.000123
2,0.344844,1300,1,0.269582,0.314838,0.045256,0.030418,0.070418,39.7,0.05,...,0.578196,0.331560,0.554039,0.108956,0.002774,0.001083,0.0,0.0,0.001273,0.000314
6,-1.769123,1300,1,0.215915,0.342292,0.126376,0.084085,0.124085,40.2,0.04,...,0.528731,0.334056,0.552506,0.106326,0.003650,0.002155,0.0,0.0,0.001056,0.000250
8,0.834843,1300,1,0.314115,0.391918,0.077802,0.014115,0.025885,39.8,0.05,...,0.583864,0.334067,0.539307,0.120735,0.003417,0.000594,0.0,0.0,0.001564,0.000316

- We can also use a thermometer to calculate temperatures to perform Toplis calculations at

In [9]:
H2O_Calc_Thermobar_eqTest2=pt.calculate_ol_liq_hygr(liq_comps=myLiquids1, ol_comps=myOls1, 
                            equationH="H_Gavr2016", eq_tests=True, P=1, equationT="T_Put2008_eq22")
H2O_Calc_Thermobar_eqTest2

,H2O_calc,Temp used for calcs,P used for calcs,Kd Meas,Kd calc (Toplis),"ΔKd, Toplis","ΔKd, Roeder","ΔKd, Matzen",SiO2_Ol,TiO2_Ol,...,Mg_Number_Liq_Fe3,Si_Ol_cat_frac,Mg_Ol_cat_frac,Fet_Ol_cat_frac,Ca_Ol_cat_frac,Al_Ol_cat_frac,Na_Ol_cat_frac,K_Ol_cat_frac,Mn_Ol_cat_frac,Ti_Ol_cat_frac
0,2.030582,1339.898440,1,0.314264,0.334334,0.020071,0.014264,0.025736,40.5,0.02,...,0.681666,0.331677,0.578691,0.084925,0.002632,0.000772,0.0,0.0,0.001179,0.000123
1,1.364482,1291.397650,1,0.175383,0.320100,0.144717,0.124617,0.164617,41.3,0.03,...,0.620707,0.331038,0.599846,0.064284,0.002662,0.001039,0.0,0.0,0.000950,0.000181
2,0.344844,1306.135888,1,0.269582,0.316037,0.046455,0.030418,0.070418,39.7,0.05,...,0.578196,0.331560,0.554039,0.108956,0.002774,0.001083,0.0,0.0,0.001273,0.000314
3,-0.344697,1262.432148,1,0.173799,0.306525,0.132726,0.126201,0.166201,40.5,0.05,...,0.523445,0.332170,0.572216,0.090539,0.002548,0.000967,0.0,0.0,0.001250,0.000309
4,2.860205,1291.067606,1,0.152172,0.326438,0.174266,0.147828,0.187828,40.5,0.00,...,0.586967,0.330886,0.600452,0.064294,0.002714,0.000963,0.0,0.0,0.000692,0.000000
5,1.508569,1298.780775,1,0.159554,0.332505,0.172951,0.140446,0.180446,40.5,0.02,...,0.565465,0.331178,0.591229,0.072488,0.002979,0.000964,0.0,0.0,0.001039,0.000123
6,-1.769123,1340.534263,1,0.215915,0.350786,0.134871,0.084085,0.124085,40.2,0.04,...,0.528731,0.334056,0.552506,0.106326,0.003650,0.002155,0.0,0.0,0.001056,0.000250
7,1.909273,1353.150970,1,0.404699,0.425290,0.020592,0.104699,0.064699,39.6,0.04,...,0.620033,0.333016,0.530297,0.131513,0.002973,0.000595,0.0,0.0,0.001353,0.000253
8,0.834843,1319.895010,1,0.314115,0.396665,0.082549,0.014115,0.025885,39.8,0.05,...,0.583864,0.334067,0.539307,0.120735,0.003417,0.000594,0.0,0.0,0.001564,0.000316
9,2.860872,1355.562175,1,0.429135,0.298723,0.130413,0.129135,0.089135,39.7,0.03,...,0.665729,0.330714,0.546417,0.117735,0.002945,0.000589,0.0,0.0,0.001411,0.000188

- We can also change the proportion of Fe3 used for the equilibrium tests

In [10]:
H2O_Calc_Thermobar_eqTest3=pt.calculate_ol_liq_hygr(liq_comps=myLiquids1, ol_comps=myOls1, 
                                               equationH="H_Gavr2016", eq_tests=True,
                                                P=1, equationT="T_Put2008_eq22", Fe3Fet_Liq=0.3)
H2O_Calc_Thermobar_eqTest3

,H2O_calc,Temp used for calcs,P used for calcs,Kd Meas,Kd calc (Toplis),"ΔKd, Toplis","ΔKd, Roeder","ΔKd, Matzen",SiO2_Ol,TiO2_Ol,...,Mg_Number_Liq_Fe3,Si_Ol_cat_frac,Mg_Ol_cat_frac,Fet_Ol_cat_frac,Ca_Ol_cat_frac,Al_Ol_cat_frac,Na_Ol_cat_frac,K_Ol_cat_frac,Mn_Ol_cat_frac,Ti_Ol_cat_frac
0,2.030582,1339.898440,1,0.359158,0.334334,0.024824,0.059158,0.019158,40.5,0.02,...,0.709915,0.331677,0.578691,0.084925,0.002632,0.000772,0.0,0.0,0.001179,0.000123
1,1.364482,1291.397650,1,0.200438,0.320100,0.119662,0.099562,0.139562,41.3,0.03,...,0.651600,0.331038,0.599846,0.064284,0.002662,0.001039,0.0,0.0,0.000950,0.000181
2,0.344844,1306.135888,1,0.308094,0.316037,0.007943,0.008094,0.031906,39.7,0.05,...,0.610379,0.331560,0.554039,0.108956,0.002774,0.001083,0.0,0.0,0.001273,0.000314
3,-0.344697,1262.432148,1,0.198628,0.306525,0.107897,0.101372,0.141372,40.5,0.05,...,0.556601,0.332170,0.572216,0.090539,0.002548,0.000967,0.0,0.0,0.001250,0.000309
4,2.860205,1291.067606,1,0.173911,0.326438,0.152527,0.126089,0.166089,40.5,0.00,...,0.618922,0.330886,0.600452,0.064294,0.002714,0.000963,0.0,0.0,0.000692,0.000000
5,1.508569,1298.780775,1,0.182347,0.332505,0.150158,0.117653,0.157653,40.5,0.02,...,0.597943,0.331178,0.591229,0.072488,0.002979,0.000964,0.0,0.0,0.001039,0.000123
6,-1.769123,1340.534263,1,0.246761,0.350786,0.104026,0.053239,0.093239,40.2,0.04,...,0.561827,0.334056,0.552506,0.106326,0.003650,0.002155,0.0,0.0,0.001056,0.000250
7,1.909273,1353.150970,1,0.462513,0.425290,0.037223,0.162513,0.122513,39.6,0.04,...,0.650950,0.333016,0.530297,0.131513,0.002973,0.000595,0.0,0.0,0.001353,0.000253
8,0.834843,1319.895010,1,0.358989,0.396665,0.037676,0.058989,0.018989,39.8,0.05,...,0.615901,0.334067,0.539307,0.120735,0.003417,0.000594,0.0,0.0,0.001564,0.000316
9,2.860872,1355.562175,1,0.490441,0.298723,0.191718,0.190441,0.150441,39.7,0.03,...,0.694759,0.330714,0.546417,0.117735,0.002945,0.000589,0.0,0.0,0.001411,0.000188